name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch

permissions:
  id-token: write   # Add this line to allow GitHub to issue an OIDC token for Azure login
  contents: read    # This is necessary to check out the repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Log in to ACR
    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    # check the contents of the repository
    - name: List Repository Contents
      run: ls -R

    # Build and push backend image
    - name: Build and Push Backend
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest ./
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest
